#ifndef REG_LIST_DATA_H
#define REG_LIST_DATA_H






REGS_BEGIN(REG_ARRAY_NAME)

REG(REG_ID_DEVICE_TYPE_VALUE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_ERROR_REGISTER_VALUE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_NUMBER_OF_ERRORS, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_0, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_9, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_10, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_11, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_12, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_13, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_14, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_15, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COB_ID_SYNC_MESSAGE_VALUE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COMMUNICATION_CYCLE_PERIOD_VALUE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SYNCHRONOUS_WINDOW_LENGTH_VALUE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_0, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_0, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COB_ID_TIME_STAMP_OBJECT_VALUE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COB_ID_EMCY_VALUE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_INHIBIT_TIME_EMCY_VALUE, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_0, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRODUCER_HEARTBEAT_TIME_VALUE, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_IDENTITY_VENDOR_ID, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_PRODUCT_CODE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_REVISION_NUMBER, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_SERIAL_NUMBER, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SYNCHRONOUS_COUNTER_OVERFLOW_VALUE_VALUE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_SERVER_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_SDO_SERVER_PARAMETER_COB_ID_CLIENT_TO_SERVER__RX_, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_SERVER_PARAMETER_COB_ID_SERVER_TO_CLIENT__TX_, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_CLIENT_PARAMETER_COUNT, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_SDO_CLIENT_PARAMETER_COB_ID_CLIENT_TO_SERVER__TX_, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_CLIENT_PARAMETER_COB_ID_SERVER_TO_CLIENT__RX_, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_CLIENT_PARAMETER_NODE_ID_OF_THE_SDO_SERVER, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_RPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_COB_ID_USED_BY_RPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_COB_ID_USED_BY_RPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_COB_ID_USED_BY_RPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_TPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_INHIBIT_TIME, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_SYNC_START_VALUE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_COB_ID_USED_BY_TPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_INHIBIT_TIME, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_SYNC_START_VALUE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_COB_ID_USED_BY_TPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_INHIBIT_TIME, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_SYNC_START_VALUE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_HIGHEST_SUB_INDEX_SUPPORTED, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_COB_ID_USED_BY_TPDO, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_TRANSMISSION_TYPE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_INHIBIT_TIME, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_EVENT_TIMER, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_SYNC_START_VALUE, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, NULL, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_1, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_2, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_3, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_4, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_5, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_6, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_7, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_8, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONF_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_CONF_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_CONF_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_SYS_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_SYS_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_SYS_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_SYS_ERRORS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Ошибки. */
REG(REG_ID_SYS_WARNINGS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Предупреждения. */
REG(REG_ID_SYS_STATE, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Состояние. */
REG(REG_ID_SYS_TIM_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_SYS_TIM_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_SYS_TIM_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_SYS_TIM_OUT_COUNTER, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Счётчик тиков. */
REG(REG_ID_MS_TIM_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_MS_TIM_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_MS_TIM_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_MS_TIM_OUT_COUNTER, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Счётчик тиков. */
REG(REG_ID_CLI_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_CLI_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_CLI_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_RGB_LED_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_RGB_LED_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_RGB_LED_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_RGB_LED_IN_DATA, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_MSDI_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_MSDI_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_MSDI_OUT_DIGITAL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG0, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG1, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG2, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG3, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG4, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG5, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG6, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG7, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_REF, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_VCC, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_NTC_TEMP_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_NTC_TEMP_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_NTC_TEMP_OUT_TEMP0, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP1, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP2, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP3, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP4, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP5, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM0, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM1, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM2, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM3, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM4, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM5, NULL, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DO_RELAY_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DO_RELAY_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DO_RELAY_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DO_RELAY_IN_DATA, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DO_NCV7608_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DO_NCV7608_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DO_NCV7608_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DO_NCV7608_IN_DATA, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DIGITAL_IN_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DIGITAL_IN_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DIGITAL_IN_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DIGITAL_IN_OUT_DATA, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Выход дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT0, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT1, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT2, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT3, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT4, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT5, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT6, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT7, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT8, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT9, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT10, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT11, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT12, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT13, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT14, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT15, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT16, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT17, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT18, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT19, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT20, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT21, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT22, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT23, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT24, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT25, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT26, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT27, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT28, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT29, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT30, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT31, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT0, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT1, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT2, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT3, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT4, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT5, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT6, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT7, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT8, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT9, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT10, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT11, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT12, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT13, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT14, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT15, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT16, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT17, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT18, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT19, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT20, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT21, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT22, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT23, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT24, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT25, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT26, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT27, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT28, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT29, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT30, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT31, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_OUT_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DIGITAL_OUT_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DIGITAL_OUT_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DIGITAL_OUT_IN_DATA, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_INVERT, NULL, REG_TYPE_U32, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT0, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT1, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT2, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT3, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT4, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT5, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT6, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT7, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT8, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT9, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT10, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT11, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT12, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT13, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT14, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT15, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT16, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT17, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT18, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT19, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT20, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT21, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT22, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT23, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT24, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT25, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT26, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT27, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT28, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT29, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT30, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT31, NULL, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_MSO_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_MSO_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_MSO_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_MSO_CHANNEL0, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL1, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL2, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL3, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL4, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL5, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL6, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL7, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL8, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL9, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL10, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL11, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL12, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL13, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL14, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL15, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL16, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL17, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL18, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL19, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL20, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL21, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL22, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL23, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL24, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL25, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL26, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL27, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL28, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL29, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL30, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL31, NULL, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_AO_DAC7562_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_AO_DAC7562_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_AO_DAC7562_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_AO_DAC7562_IN_CH_A, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_AO_DAC7562_IN_CH_B, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PANEL_LED_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_PANEL_LED_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_PANEL_LED_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_PANEL_LED_OUT_DATA, NULL, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CAN_TIM_COUNT, NULL, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_CAN_TIM_CONTROL, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_CAN_TIM_STATUS, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_CAN_TIM_OUT_COUNTER, NULL, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Счётчик тиков. */

REGS_END()


#endif /* REG_LIST_DATA_H */
