#ifndef REG_LIST_DATA_H
#define REG_LIST_DATA_H

typedef union PACKED _TIC12400_TX_FRAME {
	reg_i8_t	reg_i8[4];
	reg_i16_t	reg_i16[2];
	reg_i32_t	reg_i32;
	reg_u8_t	reg_u8[4];
	reg_u16_t	reg_u16[2];
	reg_u32_t	reg_u32;
	reg_iq7_t	reg_iq7;
	reg_iq15_t	reg_iq15;
	reg_iq24_t	reg_iq24;
} regs_data_union_t;

static regs_data_union_t regs_data_union;

REGS_BEGIN(REG_ARRAY_NAME)

REG(REG_ID_DEVICE_TYPE_VALUE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_ERROR_REGISTER_VALUE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_NUMBER_OF_ERRORS, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_0, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_9, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_10, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_11, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_12, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_13, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_14, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_15, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COB_ID_SYNC_MESSAGE_VALUE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COMMUNICATION_CYCLE_PERIOD_VALUE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SYNCHRONOUS_WINDOW_LENGTH_VALUE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_0, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_0, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COB_ID_TIME_STAMP_OBJECT_VALUE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_COB_ID_EMCY_VALUE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_INHIBIT_TIME_EMCY_VALUE, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_0, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PRODUCER_HEARTBEAT_TIME_VALUE, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_IDENTITY_VENDOR_ID, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_PRODUCT_CODE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_REVISION_NUMBER, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_IDENTITY_SERIAL_NUMBER, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SYNCHRONOUS_COUNTER_OVERFLOW_VALUE_VALUE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_SERVER_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_SDO_SERVER_PARAMETER_COB_ID_CLIENT_TO_SERVER__RX_, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_SERVER_PARAMETER_COB_ID_SERVER_TO_CLIENT__TX_, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_CLIENT_PARAMETER_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_SDO_CLIENT_PARAMETER_COB_ID_CLIENT_TO_SERVER__TX_, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_CLIENT_PARAMETER_COB_ID_SERVER_TO_CLIENT__RX_, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_SDO_CLIENT_PARAMETER_NODE_ID_OF_THE_SDO_SERVER, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_RPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_COB_ID_USED_BY_RPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_COB_ID_USED_BY_RPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_COB_ID_USED_BY_RPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_TPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_INHIBIT_TIME, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_SYNC_START_VALUE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_COB_ID_USED_BY_TPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_INHIBIT_TIME, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_SYNC_START_VALUE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_COB_ID_USED_BY_TPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_INHIBIT_TIME, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_SYNC_START_VALUE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_HIGHEST_SUB_INDEX_SUPPORTED, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_COB_ID_USED_BY_TPDO, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_TRANSMISSION_TYPE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_INHIBIT_TIME, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_EVENT_TIMER, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_SYNC_START_VALUE, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO, &regs_data_union, REG_TYPE_U8, REG_FLAG_NONE, 0x000000) /* Number of sub-entries */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_1, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_2, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_3, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_4, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_5, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_6, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_7, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_8, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CONF_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_CONF_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_CONF_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_SYS_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_SYS_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_SYS_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_SYS_ERRORS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Ошибки. */
REG(REG_ID_SYS_WARNINGS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Предупреждения. */
REG(REG_ID_SYS_STATE, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Состояние. */
REG(REG_ID_SYS_TIM_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_SYS_TIM_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_SYS_TIM_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_SYS_TIM_OUT_COUNTER, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Счётчик тиков. */
REG(REG_ID_MS_TIM_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_MS_TIM_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_MS_TIM_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_MS_TIM_OUT_COUNTER, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Счётчик тиков. */
REG(REG_ID_CLI_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_CLI_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_CLI_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_RGB_LED_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_RGB_LED_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_RGB_LED_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_RGB_LED_IN_DATA, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_MSDI_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_MSDI_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_MSDI_OUT_DIGITAL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG0, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG1, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG2, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG3, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG4, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG5, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG6, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_ANALOG7, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_REF, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSDI_OUT_VCC, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_NTC_TEMP_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_NTC_TEMP_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_NTC_TEMP_OUT_TEMP0, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP1, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP2, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP3, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP4, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_TEMP5, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM0, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM1, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM2, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM3, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM4, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_NTC_TEMP_OUT_OHM5, &regs_data_union, REG_TYPE_IQ15, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DO_RELAY_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DO_RELAY_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DO_RELAY_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DO_RELAY_IN_DATA, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DO_NCV7608_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DO_NCV7608_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DO_NCV7608_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DO_NCV7608_IN_DATA, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DIGITAL_IN_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DIGITAL_IN_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DIGITAL_IN_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DIGITAL_IN_OUT_DATA, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Выход дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT0, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT1, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT2, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT3, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT4, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT5, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT6, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT7, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT8, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT9, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT10, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT11, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT12, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT13, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT14, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT15, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT16, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT17, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT18, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT19, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT20, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT21, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT22, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT23, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT24, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT25, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT26, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT27, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT28, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT29, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT30, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_INVERT31, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр инверсии дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT0, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT1, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT2, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT3, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT4, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT5, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT6, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT7, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT8, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT9, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT10, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT11, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT12, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT13, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT14, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT15, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT16, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT17, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT18, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT19, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT20, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT21, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT22, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT23, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT24, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT25, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT26, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT27, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT28, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT29, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT30, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_IN_SELECT31, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /* Параметр выбора дискретных входов */
REG(REG_ID_DIGITAL_OUT_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_DIGITAL_OUT_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_DIGITAL_OUT_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_DIGITAL_OUT_IN_DATA, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_INVERT, &regs_data_union, REG_TYPE_U32, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT0, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT1, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT2, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT3, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT4, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT5, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT6, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT7, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT8, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT9, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT10, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT11, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT12, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT13, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT14, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT15, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT16, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT17, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT18, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT19, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT20, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT21, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT22, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT23, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT24, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT25, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT26, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT27, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT28, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT29, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT30, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_DIGITAL_OUT_SELECT31, &regs_data_union, REG_TYPE_U8, REG_FLAG_CONF, 0x000000) /*  */
REG(REG_ID_MSO_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_MSO_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_MSO_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_MSO_CHANNEL0, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL1, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL2, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL3, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL4, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL5, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL6, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL7, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL8, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL9, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL10, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL11, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL12, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL13, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL14, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL15, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL16, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL17, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL18, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL19, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL20, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL21, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL22, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL23, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL24, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL25, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL26, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL27, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL28, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL29, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL30, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_MSO_CHANNEL31, &regs_data_union, REG_TYPE_I32, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_AO_DAC7562_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_AO_DAC7562_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_AO_DAC7562_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_AO_DAC7562_IN_CH_A, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_AO_DAC7562_IN_CH_B, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_PANEL_LED_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_PANEL_LED_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_PANEL_LED_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_PANEL_LED_OUT_DATA, &regs_data_union, REG_TYPE_U16, REG_FLAG_NONE, 0x000000) /*  */
REG(REG_ID_CAN_TIM_COUNT, &regs_data_union, REG_TYPE_U8, REG_FLAG_READONLY, 0x000000) /* Number of sub entries count */
REG(REG_ID_CAN_TIM_CONTROL, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово управления. */
REG(REG_ID_CAN_TIM_STATUS, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Слово состояния. */
REG(REG_ID_CAN_TIM_OUT_COUNTER, &regs_data_union, REG_TYPE_U32, REG_FLAG_NONE, 0x000000) /* Счётчик тиков. */

REGS_END()


#endif /* REG_LIST_DATA_H */
