#ifndef  APP_REG_LIST_DATA_H
#define  APP_REG_LIST_DATA_H

static regs_data_union_t app_regs_data_union;

REGS_BEGIN(APP_REG_ARRAY_NAME)

REG(APP_REG_ID_DEVICE_TYPE_VALUE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_ERROR_REGISTER_VALUE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_NUMBER_OF_ERRORS,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_0,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_9,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_10,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_11,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_12,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_13,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_14,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRE_DEFINED_ERROR_FIELD_PRE_DEFINED_ERROR_FIELD_15,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_COB_ID_SYNC_MESSAGE_VALUE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_COMMUNICATION_CYCLE_PERIOD_VALUE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SYNCHRONOUS_WINDOW_LENGTH_VALUE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_STORE_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_0,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_STORE_PARAMETERS_STORE_PARAMETERS_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RESTORE_DEFAULT_PARAMETERS_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_0,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RESTORE_DEFAULT_PARAMETERS_RESTORE_DEFAULT_PARAMETERS_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_COB_ID_TIME_STAMP_OBJECT_VALUE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_COB_ID_EMCY_VALUE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_INHIBIT_TIME_EMCY_VALUE,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_0,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONSUMER_HEARTBEAT_TIME_CONSUMER_HEARTBEAT_TIME_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PRODUCER_HEARTBEAT_TIME_VALUE,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_IDENTITY_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_IDENTITY_VENDOR_ID,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_IDENTITY_PRODUCT_CODE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_IDENTITY_REVISION_NUMBER,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_IDENTITY_SERIAL_NUMBER,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SYNCHRONOUS_COUNTER_OVERFLOW_VALUE_VALUE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SDO_SERVER_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_SDO_SERVER_PARAMETER_COB_ID_CLIENT_TO_SERVER__RX_,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SDO_SERVER_PARAMETER_COB_ID_SERVER_TO_CLIENT__TX_,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SDO_CLIENT_PARAMETER_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_SDO_CLIENT_PARAMETER_COB_ID_CLIENT_TO_SERVER__TX_,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SDO_CLIENT_PARAMETER_COB_ID_SERVER_TO_CLIENT__RX_,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SDO_CLIENT_PARAMETER_NODE_ID_OF_THE_SDO_SERVER,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_RPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_COB_ID_USED_BY_RPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1401_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_COB_ID_USED_BY_RPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1402_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_COB_ID_USED_BY_RPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_COMMUNICATION_PARAMETER_1403_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1601_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1602_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_RPDO_MAPPING_PARAMETER_1603_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_COB_ID_USED_BY_TPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_INHIBIT_TIME,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_SYNC_START_VALUE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_COB_ID_USED_BY_TPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_INHIBIT_TIME,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1801_SYNC_START_VALUE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_COB_ID_USED_BY_TPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_INHIBIT_TIME,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1802_SYNC_START_VALUE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_HIGHEST_SUB_INDEX_SUPPORTED,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_COB_ID_USED_BY_TPDO,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_TRANSMISSION_TYPE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_INHIBIT_TIME,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_EVENT_TIMER,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_COMMUNICATION_PARAMETER_1803_SYNC_START_VALUE,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A01_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A02_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_NUMBER_OF_MAPPED_APPLICATION_OBJECTS_IN_PDO,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_NONE,  0x000000)  /*  Number  of  sub-entries  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_1,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_2,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_3,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_4,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_5,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_6,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_7,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_TPDO_MAPPING_PARAMETER_1A03_APPLICATION_OBJECT_8,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_CONF_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_CONF_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_CONF_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_SYS_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_SYS_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_SYS_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_SYS_ERRORS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Ошибки.  */
REG(APP_REG_ID_SYS_WARNINGS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Предупреждения.  */
REG(APP_REG_ID_SYS_STATE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Состояние.  */
REG(APP_REG_ID_SYS_TIM_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_SYS_TIM_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_SYS_TIM_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_SYS_TIM_OUT_COUNTER,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Счётчик  тиков.  */
REG(APP_REG_ID_MS_TIM_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_MS_TIM_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_MS_TIM_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_MS_TIM_OUT_COUNTER,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Счётчик  тиков.  */
REG(APP_REG_ID_CLI_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_CLI_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_CLI_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_RGB_LED_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_RGB_LED_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_RGB_LED_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_RGB_LED_IN_DATA,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_MSDI_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_MSDI_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_MSDI_OUT_DIGITAL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG0,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG1,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG2,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG3,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG4,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG5,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG6,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_ANALOG7,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_REF,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSDI_OUT_VCC,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_NTC_TEMP_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_NTC_TEMP_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_NTC_TEMP_OUT_TEMP0,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_TEMP1,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_TEMP2,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_TEMP3,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_TEMP4,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_TEMP5,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_OHM0,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_OHM1,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_OHM2,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_OHM3,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_OHM4,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_NTC_TEMP_OUT_OHM5,  &app_regs_data_union,  REG_TYPE_IQ15,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_DO_RELAY_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_DO_RELAY_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_DO_RELAY_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_DO_RELAY_IN_DATA,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_DO_NCV7608_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_DO_NCV7608_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_DO_NCV7608_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_DO_NCV7608_IN_DATA,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_DIGITAL_IN_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_DIGITAL_IN_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_DIGITAL_IN_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_DIGITAL_IN_OUT_DATA,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Выход  дискретных  входов  */
REG(APP_REG_ID_DIGITAL_IN_INVERT0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_INVERT31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_SELECT0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_SELECT31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  дискретного  входа  */
REG(APP_REG_ID_DIGITAL_IN_T_SET0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_SET31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_IN_T_RESET31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  бита  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_DIGITAL_OUT_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_DIGITAL_OUT_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_DIGITAL_OUT_IN_DATA,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Вход  дискретных  выходов  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_INVERT31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  инверсии  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_SELECT31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  выбора  входного  бита  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_SET31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  установки  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET0,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET1,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET2,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET3,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET4,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET5,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET6,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET7,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET8,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET9,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET10,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET11,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET12,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET13,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET14,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET15,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET16,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET17,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET18,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET19,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET20,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET21,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET22,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET23,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET24,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET25,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET26,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET27,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET28,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET29,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET30,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_DIGITAL_OUT_T_RESET31,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_CONF,  0x000000)  /*  Параметр  задержки  сброса  дискретного  выхода  */
REG(APP_REG_ID_MSO_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_MSO_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_MSO_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_MSO_CHANNEL0,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL1,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL2,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL3,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL4,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL5,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL6,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL7,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL8,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL9,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL10,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL11,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL12,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL13,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL14,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL15,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL16,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL17,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL18,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL19,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL20,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL21,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL22,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL23,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL24,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL25,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL26,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL27,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL28,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL29,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL30,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MSO_CHANNEL31,  &app_regs_data_union,  REG_TYPE_I32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_AO_DAC7562_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_AO_DAC7562_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_AO_DAC7562_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_AO_DAC7562_IN_CH_A,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_AO_DAC7562_IN_CH_B,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_PANEL_LED_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_PANEL_LED_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_PANEL_LED_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_PANEL_LED_OUT_DATA,  &app_regs_data_union,  REG_TYPE_U16,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MODBUS_REG_CAN_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_MODBUS_REG_CAN_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_MODBUS_REG_CAN_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_MODBUS_REG_CAN_REG_ID,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MODBUS_REG_CAN_REG_SIZE,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_MODBUS_REG_CAN_REG_DATA,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  */
REG(APP_REG_ID_SETTINGS_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_SETTINGS_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_SETTINGS_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_CAN_TIM_COUNT,  &app_regs_data_union,  REG_TYPE_U8,  REG_FLAG_READONLY,  0x000000)  /*  Number  of  sub  entries  count  */
REG(APP_REG_ID_CAN_TIM_CONTROL,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  управления.  */
REG(APP_REG_ID_CAN_TIM_STATUS,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Слово  состояния.  */
REG(APP_REG_ID_CAN_TIM_OUT_COUNTER,  &app_regs_data_union,  REG_TYPE_U32,  REG_FLAG_NONE,  0x000000)  /*  Счётчик  тиков.  */

REGS_END()


#endif  /*APP_REG_LIST_DATA_H */
